name: Build Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest,macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: "Install yarn and dependencies"
        run: |
          npm install -g yarn
          yarn install
      - name: "Build linux"
        if: matrix.os == 'ubuntu-latest'
        run: |
          yarn run build:linux
      - name: "Build windows"
        if: matrix.os == 'windows-latest'
        run: |
          yarn run build:win
      - name: "Build macos"
        if: matrix.os == 'macos-latest'
        run: |
          yarn run build:mac
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            dist/
          retention-days: 1
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: |
            dist/
      - name: "Prepare release"
        run: |
          mv dist/linux-unpacked/resources/app.asar dist/app.asar
          rm -rf dist/linux-unpacked
          rm -rf dist/win-unpacked
          rm -rf dist/win-ia32-unpacked
          rm -rf dist/mac
          rm -rf dist/mac-arm64
          rm -f dist/builder-debug.yml
          rm -f dist/bbg-ia32.exe
          rm -f dist/bbg-ia32.exe.blockmap
          mv dist/bbg-amd64.deb dist/bbg-${RELEASE_VERSION}-amd64.deb
          mv dist/bbg-arm64.dmg dist/bbg-${RELEASE_VERSION}-arm64.dmg
          mv dist/bbg-x64.dmg dist/bbg-${RELEASE_VERSION}-x64.dmg
          mv dist/bbg-x64.exe dist/bbg-${RELEASE_VERSION}-setup-x64.exe
          mv dist/bbg.exe dist/bbg-${RELEASE_VERSION}-setup-x86.exe
          mv dist/bbg-x64.tar.gz dist/bbg-${RELEASE_VERSION}-x64-linux.tar.gz
          mv dist/bbg-x86_64.AppImage dist/bbg-${RELEASE_VERSION}-x86_64.AppImage
          mv dist/bbg-arm64.dmg.blockmap dist/bbg-${RELEASE_VERSION}-arm64.dmg.blockmap
          mv dist/bbg.exe.blockmap dist/bbg-${RELEASE_VERSION}-x86.exe.blockmap
          mv dist/bbg-x64.dmg.blockmap dist/bbg-${RELEASE_VERSION}-x64.dmg.blockmap
          mv dist/bbg-x64.exe.blockmap dist/bbg-${RELEASE_VERSION}-x64.exe.blockmap
          cd dist && shasum -a 256 * > SHA256SUMS && cd ..
      - name: "Release"
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ github.ref_name }} / 版本 ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            The program package supports most desktop operating systems e.g, macOS, Windows and Linux. The current version supports English and Simplified Chinese as application language, despite the support for English language is currently experimental, so bugs may occur. If you have any suggestions or feedbacks, please send them to GitHub Issues. We will process them in our spare time.

            ---

            本项目支持 macOS、Windows、Linux 等常见桌面平台。目前应用程序支持设定为英语和简体中文，但对英语的支持目前仍是实验性的，因而可能会出现 Bug。如果你有任何意见或建议，请将它们发送到 GitHub Issues 中。我们会在空余时间处理这些问题。

            更新日志详见[链接](https://bbg.nekomoe.xyz/#/zh-cn/CHANGELOG)。
          files: |
            dist/*
