name: Build Release

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: "Install dependencies"
        run: |
          yarn install --frozen-lockfile
      - name: "Build Linux"
        if: matrix.os == 'ubuntu-latest'
        run: |
          yarn run build:linux
          mv dist/linux-unpacked/resources/app.asar dist/app.asar
          rm -rf dist/linux-unpacked
      - name: "Build Windows"
        if: matrix.os == 'windows-latest'
        run: |
          yarn run build:win
          rm -r dist/win-unpacked
          rm -r dist/win-ia32-unpacked
          rm dist/bbg-ia32.exe
          rm dist/bbg-ia32.exe.blockmap
      - name: "Build macOS"
        if: matrix.os == 'macos-latest'
        run: |
          yarn run build:mac
          rm -rf dist/mac
          rm -rf dist/mac-arm64
      - name: "Show build files"
        run: |
          ls dist
      - name: "Upload Linux artifacts"
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifact
          path: |
            dist/
      - name: "Upload Windows artifacts"
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifact
          path: |
            dist/
      - name: "Upload macOS artifacts"
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: macos-artifact
          path: |
            dist/
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v3
        with:
          path: |
            dist/
      - name: "Prepare release"
        run: |
          cd dist
          mv -f linux-artifact/* .
          mv -f windows-artifact/* .
          mv -f macos-artifact/* .
          rm -rf builder-debug.yml linux-artifact windows-artifact macos-artifact
          mv bbg-amd64.deb bbg-${RELEASE_VERSION}-amd64.deb
          mv bbg-arm64.dmg bbg-${RELEASE_VERSION}-arm64.dmg
          mv bbg-x64.dmg bbg-${RELEASE_VERSION}-x64.dmg
          mv bbg-x64.exe bbg-${RELEASE_VERSION}-setup-x64.exe
          mv bbg.exe bbg-${RELEASE_VERSION}-setup-x86.exe
          mv bbg-x64.tar.gz bbg-${RELEASE_VERSION}-x64-linux.tar.gz
          mv bbg-x86_64.AppImage bbg-${RELEASE_VERSION}-x86_64.AppImage
          mv bbg-arm64.dmg.blockmap bbg-${RELEASE_VERSION}-arm64.dmg.blockmap
          mv bbg.exe.blockmap bbg-${RELEASE_VERSION}-x86.exe.blockmap
          mv bbg-x64.dmg.blockmap bbg-${RELEASE_VERSION}-x64.dmg.blockmap
          mv bbg-x64.exe.blockmap bbg-${RELEASE_VERSION}-x64.exe.blockmap
          shasum -a 256 * > SHA256SUMS
          cd ..
      - name: "Show file structure"
        run: |
          tree -a
      - name: "Release"
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ github.ref_name }} / 版本 ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            The program package supports most desktop operating systems e.g, macOS, Windows and Linux. The current version supports English and Simplified Chinese as application language, despite the support for English language is currently experimental, so bugs may occur. If you have any suggestions or feedbacks, please send them to GitHub Issues. We will process them in our spare time.

            ---

            本项目支持 macOS、Windows、Linux 等常见桌面平台。目前应用程序支持设定为英语和简体中文，但对英语的支持目前仍是实验性的，因而可能会出现 Bug。如果你有任何意见或建议，请将它们发送到 GitHub Issues 中。我们会在空余时间处理这些问题。

            更新日志详见[链接](https://bbg.nekomoe.xyz/#/zh-cn/CHANGELOG)。
          files: |
            dist/*
